### ISSUE TITLE
Error: Cannot convert undefined or null to object | NextJs & NextAuth

### ISSUE THREAD

**Issue by odaytelbany** [odaytelbany/instagram-clone#1]
I am trying to do a custom page for sign in with google using NextAuth and firebase, and this is what happend.
![Screenshot 2023-08-03 103051](https://github.com/odaytelbany/instagram-clone/assets/100791118/e513bf76-988a-499d-b26e-2f5e98455cf7)

api/auth/[...nextauth]/route.js 👇

```
import NextAuth from "next-auth/next"
import GoogleProvider from "next-auth/providers/google"

export const authOptions = {
  providers: [
    GoogleProvider(
       {
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET
       }
    )
  ],
  pages: {
    signIn: '/auth'
  }
}


const handler = NextAuth(authOptions);

export { handler as GET, handler as POST }
```

And this is the custom page, the issue appears here in line 6, It seems that there is no providers 
auth/page.js 👇

```
import { getProviders, signIn } from "next-auth/react";

export default function SignIn({ providers }) {
  return (
    <>
      {Object.values(providers).map((provider) => (
        <div key={provider.id}>
          <button onClick={() => signIn(provider.id)}>Sign in with {provider.name}</button>
        </div>
      ))}
    </>
  );
}

export async function getServerSideProps() {
  const providers = await getProviders();

  return {
    props: {
      providers,
    },
  };
}
```

@mohanadft @mohammedmataralzain @Abd-Beltaji · DS:0000

**Comment by mohanadft** [comment]
Hi Oday.
I appreciate your seeking for help.

Could you please mention where is the line that throw that error?

I need more details

**Comment by odaytelbany** [comment]
the issue appears in auth/page.js , line 6, It seems that there is no providers

![Screenshot 2023-08-03 103051](https://github.com/odaytelbany/instagram-clone/assets/100791118/09a9d0e6-c2aa-4814-bc17-0ab2ebfb87ca)

**Comment by mohanadft** [comment]
I feel you.

Does your code on github have the latest updates? Including the issue

**Comment by odaytelbany** [comment]
Now it does, i commited the last update

**Comment by mohanadft** [comment]
Which route you've just visited to throw the previous error?

**Comment by odaytelbany** [comment]
its "/auth"
in local host => "http:/localhost3000/auth"

**Comment by mohanadft** [comment]
> Previous Next.js data fetching methods such as `getServerSideProps`, `getStaticProps`, and `getInitialProps` are not supported in the new App Router.

If we include this code: 
```ts
export async function getServerSideProps() {
  const providers = await getProviders();

  return {
    props: {
      providers
    }
  };
}
 ```
 
 we get this error:
 
![image](https://github.com/odaytelbany/instagram-clone/assets/78538311/ddb3f403-02ba-4663-b894-8b020e20b452)

So I guess it's something related to Next's structure for handling server side components

**Comment by mohanadft** [comment]
[here](https://github.com/vercel/next.js/issues/50424) is the main issue, you can have a look

**Comment by odaytelbany** [comment]
thank you mohanad, i appreciate your help
I will try that, hope it works

**Comment by mohanadft** [comment]
@odaytelbany 
What is the expected result when visiting `/auth`?

**Comment by mohanadft** [comment]
Moreover, if you can share with me your `.env` file, and you can delete the message after I tell you that I get it.

**Comment by odaytelbany** [comment]
### If you come later after the issue has been closed, You have to follow the new method below.

_“api/auth/[…nextauth]/route.js”_ 👇


```
import NextAuth from "next-auth/next"
import GoogleProvider from "next-auth/providers/google"

export const authOptions = {
  providers: [
    GoogleProvider(
       {
        clientId: process.env.GOOGLE_CLIENT_ID,
        clientSecret: process.env.GOOGLE_CLIENT_SECRET
       }
    )
  ],
  pages: {
    signIn: '/auth'
  }
}


const handler = NextAuth(authOptions);

export { handler as GET, handler as POST }
```

As you see **NextAuth()** take an object of customization options, like: providers, pages, theme, …
Most of them are optional, but the providers should have your sign in method as you see I used Google Provider here.

============================================================================

_“auth/page.js”_ The custom page 👇

```
'use client';

import React, { use } from 'react';
import { getProviders } from 'next-auth/react';
import SignInBtn from '../../components/SignInBtn/SignInBtn';

async function getData() {
  const providers = await getProviders();

  return providers;
}

export default function SignIn() {
  const providers = use(getData());

  return (
    <>
      {Object.values(providers).map(provider => {
        return <SignInBtn name={provider.name} key={provider.id} />;
      })}
    </>
  );
}

```

The main problem that caused my issue is the “**getServerSideProps**” function, becaue its not supported in app/.
What is the alternative to that?

-The alternative is “**use**” hook, of course when we use  hooks, we have to define the component as a client component using “use client” above.
Read the code above and compare it with the code In that caused the issue to understand, how it works now
