### ISSUE TITLE
Does this repo accept contributions?

### ISSUE THREAD

**Issue by petya0927** [odaytelbany/instagram-clone#3]
I found this repo in my feed a couple of days ago and wanted to contribute, because it could be a great learning opportunity about contributions. But at the same time I don't want to interfere if this is your own project. 

Anyway, it's great and keep up guys!

**Comment by odaytelbany** [comment]
No problems bro, go ahead
I apply anything new I learn to this repo

**Comment by petya0927** [comment]
Okay, thanks! If you have anything in mind, create an issue and I'm more than happy to help.
